routes/web.php
<?php

use App\Immobili;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','ImmobiliController@index');

Auth::routes();

Route::get('/home', 'ImmobiliController@index')->name('home');
Route::get('/{immobile}/immobile','ImmobiliController@details');
// Route::get('/favorite','ImmobiliController@favorite');

Route::group(['middleware' =>'auth'], function(){
  Route::get('/create','ImmobiliController@create');
  Route::post('/save','ImmobiliController@store')->name('save');
  Route::post('/{immobile}/addfavorite','ImmobiliController@addFavorite');
  Route::delete('/{immobile}/removefavorite','ImmobiliController@removeFavorite');
});

app/Favorite.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Favorite extends Model
{

}

app/Immobili.php
<?php

namespace App;
use App\Favorite;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Immobili extends Model
{

  public function GetPathAttribute(){
    $url = $this->image;
    if(!stristr($url,'http')){
      $url = 'storage/'.$this->image;
    }
    return $url;
  }

  public function getIsfavoriteAttribute(){
    $favorite = Favorite::where('user_id',Auth::user()->id)->where('immobile_id',$this->id)->get();
    if(!$favorite->isEmpty()){
      return true;
    }
    return false;
  }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ImmobiliController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Immobili;
use DB;
use Illuminate\Support\Facades\Auth;
use App\Favorite;

class ImmobiliController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $req)
    {
      if($req->has('ordine') && $req->has('ordine2') ){
        $immobili = Immobili::orderBy($req->get('ordine'),$req->get('ordine2'))->get();
      }
        elseif($req->has('ordine')){
          $immobili = Immobili::orderBy($req->get('ordine'),'ASC')->get();
        }
        else {
        $immobili = Immobili::orderBy('created_at','DESC')->get();
      }
        return view('pages.home',['immobili' => $immobili]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.addImmobile');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $immobile = new Immobili();
        $immobile->name = $request->name;
        $immobile->description = $request->description;
        $immobile->image= "";
        $immobile->price = $request->price;
        $immobile->mq = $request->metri;
        $immobile->user_id = Auth::user()->id;
        $res = $immobile->save();
        if($res){
          $resStore = $this->StoreImage($immobile->id,request(),$immobile);
        if($resStore)
          $res = $immobile->save();
        }
        return redirect()->to('/');

    }

    public function details(Immobili $immobile){
      return view('pages.details',['immobile'=>$immobile]);
    }

    // public function favorite(){
    //   return view('pages.home',['immobili' => $immobili]);
    // }


    public function addFavorite($immobile, Request $request){
      $favorite = new Favorite();
      $favorite->immobile_id = $immobile;
      $favorite->user_id = Auth::user()->id;
      $favorite->save();
      return "true";
    }

    public function removeFavorite($immobile){
      $res = Favorite::where('immobile_id',$immobile)->where('user_id',Auth::user()->id)->delete();
      return $res;
    }

    public function StoreImage($id,Request $req, &$immobile){
      if(!$req->hasFile('path'))
        return false;


      $file = $req->file('path');
      if(!$file->isValid())
        return false;
      //$fname = $file->store(env('ALBUM_THUMB_DIR')); NOME CASUALE
      $fname = $id.'.'.$file->extension();
      $fname = $file->storeAs(env('IMG_DIR'),$fname);
      $immobile->image = $fname;
      return true;
  }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/pages/addImmobile.blade.php
@extends('templates.layout')

@section('name','CREATE')

@section('content')
<h1>NUOVO IMMOBILE</h1>
  <form class="" action="{{route('save')}}" method="POST" enctype="multipart/form-data">
    {{csrf_field()}}
    <div class="form-group">
      <label for="">Nome</label>
      <input name="name" type="text" class="form-control" required placeholder="Nome">
    </div>
    <div class="form-group">
      <label for="">Descrizione</label>
      <input name="description" type="text" class="form-control" required placeholder="Descrizione">
    </div>
    <div class="form-group">
    <label for="">Image</label>
    <input name="path" type="file" class="form-control" placeholder="Name" value="">
    </div>
    <div class="form-group">
      <label for="">Prezzo</label>
      <input name="price" type="number" min="50000" step="10000" class="form-control" required placeholder="Prezzo">
    </div>
    <div class="form-group">
      <label for="">Metri Quadri</label>
      <input name="metri" type="number" min="60" step="10" class="form-control" required placeholder="Metri Quadri">
    </div>
    <button class="btn btn-primary" type="submit">INVIA</button>
  </form>

@endsection

resources/views/pages/details.blade.php
@extends('templates.layout')

@section('title',$immobile->name)

@section('content')
<h1>{{$immobile->name}}</h1>
<p>data {{$immobile->created_at}}</p>
<p>PREZZO: {{$immobile->price}} €</p>
<p>MQ: {{$immobile->mq}} m</p>
<h5>Description</h5>
<p>{{$immobile->description}}</p>
@stop

resources/views/pages/home.blade.php
@extends('templates.layout')

@section('title','PORTALE')

@section('content')
<form class="" action="/" method="get">
  <div class="form-group">
        <select required name="ordine" id="ordine">
          <option value="">ORDINA</option>
          <option value="price">prezzo</option>
          <option value="mq">mq</option>
          <option value="created_at">data</option>
        </select>
        <select required name="ordine2" id="ordine">
          <option value="">--</option>
          <option value="ASC">ASC</option>
          <option value="DESC">DESC</option>
        </select>
        <button type="submit">Invia</button>
  </div>
</form>


@stop

@section('contentblog')
  @forelse ($immobili as $immobile )
    @component('components.article')
      @slot('image_url',asset($immobile->path))
      @slot('name', $immobile->name)
      @slot('data', $immobile->created_at)
      @slot('price', $immobile->price)
      @slot('metri_q', $immobile->mq)
      @slot('description', $immobile->description)
        <div class="" style="margin-bottom:8px;">
          <a  href="{{$immobile->id}}/immobile" class="btn btn-primary"> DETTAGLI</a>
        </div>
        @guest
        @else
          @if ($immobile->isfavorite)
            <div class="test2">
              <a id="fav2" href="{{$immobile->id}}/removefavorite" class="btn btn-danger"> RIMUOVI DAI PREFERITI </a>
            </div>
          @else
              <div class="test">
                <a id="fav" href="{{$immobile->id}}/addfavorite" class="btn btn-primary"> Favorite </a>
              </div>
          @endif
        @endguest

    @endcomponent
  @empty
    <h1>NO IMAGES</h1>
  @endforelse
@stop

@section('script')
  @parent
  <script type="text/javascript">
    $('document').ready(function(){
      $('.test').on('click','#fav',function(e){
        e.preventDefault();
        div = $(this);
        $.ajax({
          url: $(this).attr('href'),
          type: 'POST',
          data: {
            '_token' : '{{csrf_token()}}'
          },
          success: function(out){
            alert('aggiunto ai preferiti');
            div.remove();
          }
        });
      });

      $('.test2').on('click','#fav2',function(e){
        e.preventDefault();
        div = $(this);
        $.ajax({
          url: $(this).attr('href'),
          type: 'DELETE',
          data: {
            '_token' : '{{csrf_token()}}'
          },
          success: function(out){
            alert('eliminato dai preferiti');
            div.remove();
          }
        });
      });
    });
  </script>
@stop

resources/views/templates/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>@yield('title')</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->


    <meta name="theme-color" content="#563d7c">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media(min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .container {
            margin-top: 70px;
        }

        #content {
            margin-bottom: 70px;
        }

        .container h1 {
            text-align: center;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="navbar-top-fixed.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#"> @yield('title') </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">HOME<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/create">AGGIUNGI IMMOBILE</a>
                </li>
                {{-- @guest
                  @else
                    <li class="nav-item">
                        <a class="nav-link" href="/favorite">PREFERITI</a>
                    </li>
                @endguest --}}

                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            {{-- LO COPIO DAL FILE Layouts/app --}}
             <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
            @endif
            @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
            @endguest
            </ul>


        </div>
    </nav>

    <main role="main" class="container">
        <div class="row">
            <div class="col-sm-12" id="content">
                @yield('content')
            </div>
            @yield('contentblog')
        </div>
    </main>
    @section('script')
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    @show
</body>

</html>